language: python
python:
  - 3.5
 
env:
  - TOXENV=py26-stix111
  - TOXENV=py26-stix120old
  - TOXENV=py26-stix120
  - TOXENV=py27-stix111
  - TOXENV=py27-stix120old
  - TOXENV=py27-stix120

install:
  - pip install -U tox

script:
  - tox

notifications:
  email:
    - stix-commits-list@lists.mitre.org
